### ISSUE TITLE
Add unique sounds for selecting a piece, moving a piece, jumping a piece, getting a king piece, and winning. 

### ISSUE THREAD

**Issue by joeyhage** [imapepper/checkersmis307#6]

**Comment by amtuel** [comment]
I added the unique sounds, but it appears to be a pain in figuring out how to get Java to play the mp3s.

**Comment by joeyhage** [comment]
Looks like a good start though! I'm surprised with the GUI they don't have something better for playing MP3s. I'll do some research. Maybe there is a library we can add.

**Comment by joeyhage** [comment]
@amtuel See commit: deae3bc

**Comment by amtuel** [comment]
Looks great!
